# Generated by Django 5.0.6 on 2024-07-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='creator',
            new_name='quiz_creator',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='title',
            new_name='quiz_title',
        ),
        migrations.AddField(
            model_name='question',
            name='question_num',
            field=models.IntegerField(default=0),
        ),
    ]
